// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace prj052.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251215132639_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MEAL", b =>
                {
                    b.Property<string>("IdMeal")
                        .HasColumnType("varchar(255)")
                        .HasAnnotation("Relational:JsonPropertyName", "idMeal");

                    b.Property<string>("StrArea")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strArea");

                    b.Property<string>("StrCategory")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strCategory");

                    b.Property<string>("StrCreativeCommonsConfirmed")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strCreativeCommonsConfirmed");

                    b.Property<string>("StrImageSource")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strImageSource");

                    b.Property<string>("StrIngredient1")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient1");

                    b.Property<string>("StrIngredient10")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient10");

                    b.Property<string>("StrIngredient11")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient11");

                    b.Property<string>("StrIngredient12")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient12");

                    b.Property<string>("StrIngredient13")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient13");

                    b.Property<string>("StrIngredient14")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient14");

                    b.Property<string>("StrIngredient15")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient15");

                    b.Property<string>("StrIngredient16")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient16");

                    b.Property<string>("StrIngredient17")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient17");

                    b.Property<string>("StrIngredient18")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient18");

                    b.Property<string>("StrIngredient19")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient19");

                    b.Property<string>("StrIngredient2")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient2");

                    b.Property<string>("StrIngredient20")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient20");

                    b.Property<string>("StrIngredient3")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient3");

                    b.Property<string>("StrIngredient4")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient4");

                    b.Property<string>("StrIngredient5")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient5");

                    b.Property<string>("StrIngredient6")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient6");

                    b.Property<string>("StrIngredient7")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient7");

                    b.Property<string>("StrIngredient8")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient8");

                    b.Property<string>("StrIngredient9")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strIngredient9");

                    b.Property<string>("StrInstructions")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strInstructions");

                    b.Property<string>("StrMeal")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeal");

                    b.Property<string>("StrMealAlternate")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMealAlternate");

                    b.Property<string>("StrMealThumb")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMealThumb");

                    b.Property<string>("StrMeasure1")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure1");

                    b.Property<string>("StrMeasure10")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure10");

                    b.Property<string>("StrMeasure11")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure11");

                    b.Property<string>("StrMeasure12")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure12");

                    b.Property<string>("StrMeasure13")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure13");

                    b.Property<string>("StrMeasure14")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure14");

                    b.Property<string>("StrMeasure15")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure15");

                    b.Property<string>("StrMeasure16")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure16");

                    b.Property<string>("StrMeasure17")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure17");

                    b.Property<string>("StrMeasure18")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure18");

                    b.Property<string>("StrMeasure19")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure19");

                    b.Property<string>("StrMeasure2")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure2");

                    b.Property<string>("StrMeasure20")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure20");

                    b.Property<string>("StrMeasure3")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure3");

                    b.Property<string>("StrMeasure4")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure4");

                    b.Property<string>("StrMeasure5")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure5");

                    b.Property<string>("StrMeasure6")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure6");

                    b.Property<string>("StrMeasure7")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure7");

                    b.Property<string>("StrMeasure8")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure8");

                    b.Property<string>("StrMeasure9")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strMeasure9");

                    b.Property<string>("StrSource")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strSource");

                    b.Property<string>("StrTags")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strTags");

                    b.Property<string>("StrYoutube")
                        .HasColumnType("longtext")
                        .HasAnnotation("Relational:JsonPropertyName", "strYoutube");

                    b.HasKey("IdMeal");

                    b.ToTable("Meals");
                });
#pragma warning restore 612, 618
        }
    }
}
